---
branches:
  only:
    - master
language: ruby
bundler_args: --without development
script: "bundle exec rake spec SPEC_OPTS='--format documentation'"
rvm:
  - 1.8.7
  - 1.9.3
  - 2.0.0
env:
  matrix:
  - PUPPET_GEM_VERSION="~> 2.7.0"
  - PUPPET_GEM_VERSION="~> 3.3.0"
matrix:
  fast_finish: true
  exclude:
  - rvm: 1.9.3
    env: PUPPET_GEM_VERSION="~> 2.7.0"
  - rvm: 2.0.0
    env: PUPPET_GEM_VERSION="~> 2.7.0"
notifications:
  email: false
after_success:
- git clone -q git://github.com/puppetlabs/ghpublisher.git .forge-release
- .forge-release/publish
before_install:
- gem update --system 2.1.11
- gem --version
comments:
- Temporary workaround for broken Rubygems on Travis

